#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path


SPECIAL_TOKENS = {
    "qt": "Qt",
    "ui": "UI",
    "qss": "QSS",
    "ws": "WS",
    "git": "Git",
    "ios": "iOS",
    "pdf": "PDF",
    "html": "HTML",
    "mcp": "MCP",
    "devops": "DevOps",
    "wsid": "WSID",
    "sms": "SMS",
    "wa": "WA",
    "cpp": "CPP",
    "csharp": "CSharp",
    "ocr": "OCR",
    "api": "API",
    "spec": "Spec",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backfill agents/openai.yaml for skills missing it.")
    parser.add_argument("root", help="Skills root")
    parser.add_argument("--apply", action="store_true", help="Write files instead of printing the plan")
    parser.add_argument(
        "--overwrite-autogenerated",
        action="store_true",
        help="Refresh files whose default_prompt matches this script's autogenerated pattern.",
    )
    return parser.parse_args()


def title_from_name(name: str) -> str:
    parts = []
    for token in name.split("-"):
        parts.append(SPECIAL_TOKENS.get(token, token.capitalize()))
    return " ".join(parts)


def extract_frontmatter(skill_path: Path) -> tuple[str, str]:
    text = skill_path.read_text(encoding="utf-8")
    match = re.match(r"---\n(.*?)\n---\n", text, flags=re.S)
    if not match:
        raise ValueError(f"Missing frontmatter: {skill_path}")
    frontmatter = match.group(1)
    name_match = re.search(r"^name:\s*(.+)$", frontmatter, flags=re.M)
    if not name_match:
        raise ValueError(f"Missing skill name: {skill_path}")
    block_match = re.search(r"^description:\s*>\s*\n(?P<body>(?:^[ \t].*\n?)*)", frontmatter, flags=re.M)
    if block_match:
        raw_desc = block_match.group("body")
    else:
        desc_match = re.search(r"^description:\s*(.+)$", frontmatter, flags=re.M)
        raw_desc = desc_match.group(1).strip().strip('"') if desc_match else ""
    description = " ".join(line.strip() for line in raw_desc.splitlines()).strip()
    return name_match.group(1).strip().strip('"'), description


def short_description(description: str, fallback_name: str) -> str:
    if not description:
        return f"Use {title_from_name(fallback_name)} for its named workflow"
    cleaned = re.sub(r"\s+", " ", description).strip()
    cleaned = cleaned.lstrip("\"'“”‘’")
    prefix_patterns = [
        r"^Use when the user asks to\s+",
        r"^Use when the user\s+",
        r"^Use when\s+",
        r"^Use for\s+",
        r"^When the user asks to\s+",
        r"^When the user\s+",
    ]
    for pattern in prefix_patterns:
        cleaned = re.sub(pattern, "", cleaned, flags=re.I)
    if ":" in cleaned:
        left, right = cleaned.split(":", 1)
        if len(left) < 48:
            cleaned = right.strip()
    parts = re.split(r"[。.!?;；]", cleaned, maxsplit=1)
    result = parts[0].strip()
    if len(result) > 90:
        result = result[:87].rstrip() + "..."
    return result


def default_prompt(name: str, short_desc: str) -> str:
    return f"Use ${name} when this task needs: {short_desc}."


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_yaml(name: str, description: str) -> str:
    short_desc = short_description(description, name)
    return (
        "interface:\n"
        f"  display_name: {yaml_quote(title_from_name(name))}\n"
        f"  short_description: {yaml_quote(short_desc)}\n"
        f"  default_prompt: {yaml_quote(default_prompt(name, short_desc))}\n"
    )


def is_autogenerated(target: Path, skill_name: str) -> bool:
    if not target.exists():
        return False
    text = target.read_text(encoding="utf-8")
    return f"default_prompt: \"Use ${skill_name} when this task needs:" in text


def main() -> int:
    args = parse_args()
    root = Path(args.root)
    skill_dirs = sorted([p for p in root.iterdir() if p.is_dir() and (p / "SKILL.md").exists()], key=lambda p: p.name)
    pending: list[tuple[Path, str]] = []
    for skill_dir in skill_dirs:
        target = skill_dir / "agents" / "openai.yaml"
        name, description = extract_frontmatter(skill_dir / "SKILL.md")
        if target.exists() and not (args.overwrite_autogenerated and is_autogenerated(target, name)):
            continue
        pending.append((target, render_yaml(name, description)))

    if not args.apply:
        for target, _ in pending:
            print(target)
        return 0

    for target, content in pending:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        print(f"WROTE {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
